### ISSUE TITLE
[FEATURE] Add contributing guidelines

### ISSUE THREAD

**Issue by Panquesito7** [Tech-Phantoms/Tech-Phantoms#291]
**Is your feature request related to a problem? Please describe.**

I think contributing guidelines are needed. Plus, in the readme there's a broken link to the contributing guidelines.
I can help in setting the contributing guidelines. If you need any help, please let me know. 🙂

**Describe the solution you'd like**

Add contributing guidelines to the repository.

**Describe alternatives you've considered**

None. 🙂

**Comment by adityagi02** [comment]
I'll do it. You can assign it to me.

**Comment by Panquesito7** [comment]
> I'll do it. You can assign it to me.

Assigned.

**Comment by aniketk13** [comment]
Hey @Panquesito7, you can close this issue too!
