### ISSUE TITLE
Netlify badge in readme is broken

### ISSUE THREAD

**Issue by Souvikns** [Tech-Phantoms/Tech-Phantoms#293]
Since I deleted the netlify project, now the netlify badge is broken, I think we should remove it or update it. 
> This is a document issue so opening it for Hacktoberfest

**Comment by S0C7** [comment]
Hi @Souvikns , I've created a Pull Request for this issue: https://github.com/Tech-Phantoms/Tech_Phantoms_website/pull/294.
