### ISSUE TITLE
Create NextJS Starter Code [Typescript][TailwindCSS]

### ISSUE THREAD

**Issue by imabp** [Tech-Phantoms/Tech-Phantoms#318]
### What would you like to share?

As we are migrating to NextJS, it will be great idea, to have a NextJS, TailwindCSS Typescript starter code to canary branch. 
Do not delete any sensitive files like, `CNAME`.

### Would you like to work on this issue?

- [ ] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aniketk13** [comment]
This could be closed now I guess.
