### ISSUE TITLE
Contributing Guidelines page not working.

### ISSUE THREAD

**Issue by aniketk13** [Tech-Phantoms/Tech-Phantoms#322]
### What would you like to share?

On Clicking the Contributing Guidelines link in Readme, it lead me to a "Page not found"

### Additional information

Probably the page has not been created. 

### Would you like to work on this issue?

- [X] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
Nice catch 👍 yeah, we have to create a contributing guidelines file. There's an issue for that: #291.

**Comment by aniketk13** [comment]
> Nice catch 👍 yeah, we have to create a contributing guidelines file. There's an issue for that: #291.

Hey, I have created it. Could you please verify it?
